{
	admin off
	auto_https off
}

http://{$ZMODO_BIND_IP}:8090 {
	encode zstd gzip

	@protectedMedia path /whep/* /hls/*
	forward_auth @protectedMedia web:8090 {
		uri /api/auth/authorize
	}

	handle_path /whep/* {
		reverse_proxy mediamtx:8889
	}

	handle_path /hls/* {
		reverse_proxy mediamtx:8888
	}

	handle {
		reverse_proxy web:8090
	}

	header {
		X-Content-Type-Options "nosniff"
		Referrer-Policy "no-referrer"
		-Server
	}
}
